### ISSUE TITLE
Angular compatibility 

### ISSUE THREAD

**Issue by emilyspitzer** [yafred/leaflet-responsive-popup#10]
Hi,
Has anyone written libraries to make this compatible with Angular 6?
Thanks!
Emily

**Comment by yafred** [comment]
Hi,

> make this compatible with Angular 6

Can you expand on what this means ?

**Comment by manojguptatn** [comment]
so  we have used https://github.com/Asymmetrik/ngx-leaflet in our angular application. We could not find the responsive popup library as yours which is compatible with ngx-leaflet. 
We wanted to check if you are planning to convert the js version with ngx-leaflet supported version.

The goal i have is to  implement your solution on responsive popup in ngx-leaflet.

Please guide me in this regard.

**Comment by emilyspitzer** [comment]
> so we have used https://github.com/Asymmetrik/ngx-leaflet in our angular application. We could not find the responsive popup library as yours which is compatible with ngx-leaflet.
> We wanted to check if you are planning to convert the js version with ngx-leaflet supported version.
> 
> The goal i have is to implement your solution on responsive popup in ngx-leaflet.
> 
> Please guide me in this regard.

Yes, we are hoping to not have to translate into typescript from scratch.

**Comment by yafred** [comment]
@manojguptatn It seems that ngx-leaflet does not support Popup at all
Did you find a way to show a Popup ?

**Comment by yafred** [comment]
Happy new year!

https://github.com/yafred/ngx-leaflet-responsive-popup/

**Comment by emilyspitzer** [comment]
Thank you, this was super helpful! Happy New year to you as well!
