### ISSUE TITLE
CSS Demo page error

### ISSUE THREAD

**Issue by Necromunger** [yafred/leaflet-responsive-popup#11]
https://yafred.github.io/leaflet-responsive-popup/popup-css-rtl

This demo page is looking a bit messed up at the moment with all the popups stuck on the left side of the page.

**Comment by yafred** [comment]
You are absolutely right ...

It's not really a bug as such because it works fine on a map: https://yafred.github.io/leaflet-responsive-popup/default-marker-tip-rtl

But it's annoying :(

Thanks noticing

If anybody passing by has an idea ... I'd welcome the fix
