### ISSUE TITLE
autoPan and keepInView ignored

### ISSUE THREAD

**Issue by robslotboom** [yafred/leaflet-responsive-popup#12]
Hi yafred,

Thank you for the nice responsive solution.
Is working very well but I found an issue.
AutoPan and KeepInView have no effect.

I don’t know if this is on purpose.

Cheers,
Robert

**Comment by yafred** [comment]
Hi,
Yes this is on purpose.
This would be a contradiction:
- Both autoPan and keepInView move the map to make sure a popup stays fully visible.
- The purpose of leaflet-reponsive-popup is to make sure a popup is visible WITHOUT moving the map.
