### ISSUE TITLE
Issues with popup on the right hand side using react

### ISSUE THREAD

**Issue by lm93547** [yafred/leaflet-responsive-popup#13]
Hello, I keep running into a error with the popup on the right hand side of a react leaflet map. I am right in assuming that this popup here should shift to the left of the marker? No other issues other than this?

![Screenshot from 2020-02-07 23-53-43](https://user-images.githubusercontent.com/49888000/74023831-71a2ad80-4a05-11ea-8354-744285adc7c4.png)

**Comment by lm93547** [comment]
I have tried `autoPanPadding: [10,10], offset: [10,10]` but with no effect. Any ideas would be greatly appreciated.

**Comment by yafred** [comment]
Is there a way you can put your example online ?

**Comment by lm93547** [comment]
Unfortunately not due to the closed nature of the project. I can post a snippet of the code I am using to initialise the responsive popup if that would help?

**Comment by lm93547** [comment]
https://github.com/serge-web/serge/tree/responsive-popup-clean 
Try branching from this and running the project like it says in the instructions

**Comment by yafred** [comment]
I'll have a look ...

My guess is that the right hand panel is not taken into account when calculating the position (because it covers the map)

Try and use regular L.Popup with autoPan: true to see if it behaves the same way.

**Comment by lm93547** [comment]
Yes I thought the same, but the “map” when inspected is the map only, the sidebar does not cover it. This can be replicated by “inspecting element” on the map div, and it just highlights the map element. But I will try the regular popup and get back to you.

**Comment by lm93547** [comment]
Just tested using `L.Popup` with `autoPan: true` and the same behavior is seen.

**Comment by lm93547** [comment]
So when console.logging `map.getSize` the map size is consistent with the actual size, and not the size plus the space under the right hand side bar:

![Screenshot from 2020-02-09 23-46-05](https://user-images.githubusercontent.com/49888000/74100692-9aa67800-4b96-11ea-808d-49396d995e0b.png)

**Comment by yafred** [comment]
I'm struggling getting the environment right :(

Is the [attribution ](https://leafletjs.com/index.html) also hidden ?

**Comment by lm93547** [comment]
Best way I found was to clone my branch then do `yarn install`
then `yarn start:server`
then do `yarn build` inside the serge folder cloned. And set the local host ip in you `env` file to whatever your local IP is.

**Comment by yafred** [comment]
Windows is not supported :(

**Comment by yafred** [comment]
Please reopen if your case works fine with L.Popup but not with L.ResponsivePopup
