### ISSUE TITLE
Bad popup opening location with rigth to left text direction

### ISSUE THREAD

**Issue by frodrigo** [yafred/leaflet-responsive-popup#8]
With HTML page set with `direction: rtl` the pop does not open on the right location. It's OK on vanilla leaflet without leaflet-responsive-popup.

On https://jsfiddle.net/Lypco4w8/1/ not the `style="direction: rtl;"` and click on the marker.

![image](https://user-images.githubusercontent.com/1785486/47604551-badf1180-d9fb-11e8-9840-8512f5527871.png)

**Comment by yafred** [comment]
Yes, good catch. 
At first glance, I have no idea why ... needs a bit of brain work.

Do you need rtl on the map itself ?
If not, a simple work-around would be to add `direction: ltr;` to the style of the map

```
<body style="direction: rtl;">
<div id="map2" style="height:400px; width:400px; margin-bottom: 20px; direction: ltr;"></div>
</body>
```

**Comment by frodrigo** [comment]
Yes need id for control, popup content and so on.

I have this as work around, but the popup glitch:
```
.leaflet-popup {                                                                                                     
  position: relative !important;                                                                                     
}  
```

**Comment by yafred** [comment]
I think I fixed it: https://yafred.github.io/leaflet-responsive-popup/open-on-map-tip-rtl
Please add following to your page to test it

`<link rel="stylesheet" href="https://yafred.github.io/leaflet-responsive-popup/assets/leaflet.responsive.popup.rtl.css" />
`
I'll promote it if it works for you

**Comment by frodrigo** [comment]
Works for me, in rtl and ltr. Thank you.

**Comment by yafred** [comment]
Promoted to 0.5.0
